---
name: code-npm-release
run-name: "Release labeled ${{ inputs.RELEASE_TYPE || 'in PR' }}"

concurrency: code-release-${{ github.ref }}

on:
  pull_request:
    types: [closed]
    branches: ["main", "main-*"]
    paths: ["code/**", ".github/workflows/code**"]
  workflow_dispatch:
    inputs:
      BASELINE:
        description: "Baseline branch"
        required: true
        default: "main"
      RELEASE_TYPE:
        description: "Release type to use"
        required: true
        default: "release-type/minor"
        type: choice
        options:
          - "release-type/hotfix"
          - "release-type/multi-hotfix"
          - "release-type/major"
          - "release-type/minor"
          - "release-type/patch"

jobs:
  prepare-release:
    name: Prepare Release
    if: github.event_name == 'workflow_dispatch'
      || (github.event.pull_request.merged == true && !contains(join(github.event.pull_request.labels.*.name, ', '), 'skip-release')
      && (contains(join(github.event.pull_request.labels.*.name, ', '), 'release-type')
      || vars.DEVELOPMENT_FLOW == 'trunk-based-development' ))
    runs-on: ubuntu-24.04
    outputs:
      release_version: ${{ steps.update-changelog.outputs.version }}
      release_type: ${{ steps.determine-type.outputs.release_type }}
      baseline_branch: ${{ steps.get-params.outputs.baseline_branch }}
    steps:
      - name: Validate admin permissions
        id: permission-check
        uses: actions/github-script@v7
        with:
          script: |
            const { data } = await github.rest.repos.getCollaboratorPermissionLevel({
              owner: context.repo.owner,
              repo: context.repo.repo,
              username: context.actor
            });

            const permission = data.permission;
            core.info(`User permission level: ${permission}`);

            if (permission !== 'admin') {
              core.setFailed(`User @${context.actor} is not a repository admin.`);
            }

      - name: Get input parameters
        id: get-params
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            RELEASE_LABELS="${{ github.event.inputs.RELEASE_TYPE }}"
          else
            RELEASE_LABELS="${{ join(github.event.pull_request.labels.*.name, ', ') }}"
            if [[ $RELEASE_LABELS != *release-type/* ]]; then
              RELEASE_LABELS="$RELEASE_LABELS, release-type/minor"
            fi
          fi
          echo "RELEASE_LABELS=$RELEASE_LABELS" >> "$GITHUB_ENV"
          BASELINE_BRANCH=${{ github.event.inputs.BASELINE || github.ref }}
          echo "baseline_branch=${BASELINE_BRANCH#refs/heads/}" >> "$GITHUB_OUTPUT"

      - name: Checkout merge commit
        uses: actions/checkout@v4
        with:
          ref: ${{ steps.get-params.outputs.baseline_branch }}
          fetch-depth: 0
          persist-credentials: false

      - name: Determine release type
        id: determine-type
        run: |
          if [[ "$RELEASE_LABELS" == *"release-type/hotfix"* ]] || [[ "$RELEASE_LABELS" == *"release-type/multi-hotfix"* ]] || [[ "$RELEASE_LABELS" == *"release-type/patch"* ]]; then
            RELEASE_TYPE=patch
          elif [[ "$RELEASE_LABELS" == *"release-type/major"* ]]; then
            RELEASE_TYPE=major
          else
            RELEASE_TYPE=minor
          fi
          echo "RELEASE_VERSION=$RELEASE_TYPE" >> "$GITHUB_ENV"
          echo "release_type=$RELEASE_TYPE" >> "$GITHUB_OUTPUT"

      - name: Update CHANGELOG.md
        id: update-changelog
        uses: release-flow/keep-a-changelog-action@v3.0.0
        with:
          command: bump
          version: ${{ env.RELEASE_VERSION }}
          changelog: code/CHANGELOG.md
          fail-on-empty-release-notes: false
          keep-unreleased-section: true
          tag-prefix: ""

  publish-release:
    name: Publish Release to NPM
    needs: prepare-release
    uses: ./.github/workflows/code-npm_node-publish-reusable.yml
    with:
      publish-type: RELEASE
      checkout-ref: ${{ needs.prepare-release.outputs.baseline_branch }}
      release-version: ${{ needs.prepare-release.outputs.release_version }}
      working-directory: code
      asdf-version: "0.18.0"
    secrets: inherit

  finalize-release:
    name: Finalize Release
    needs: [prepare-release, publish-release]
    runs-on: ubuntu-24.04
    env:
      ASDF_BRANCH_VERSION: 0.18.0
    steps:
      - name: Checkout baseline branch
        uses: actions/checkout@v4
        with:
          ref: ${{ needs.prepare-release.outputs.baseline_branch }}
          fetch-depth: 0
          persist-credentials: false

      - name: Setup asdf Cache
        id: asdf-cache
        uses: actions/cache@v4
        continue-on-error: true
        with:
          path: ~/.asdf
          key: ${{ runner.os }}-asdf-${{ env.ASDF_BRANCH_VERSION }}-${{ hashFiles('code/.tool-versions') }}

      - name: Save tool-versions content
        run: |
          {
            echo "TOOL_VERSIONS<<EOF"
            cat code/.tool-versions
            echo "EOF"
          } >> "$GITHUB_ENV"

      - name: Setup asdf environment
        uses: asdf-vm/actions/install@1902764435ca0dd2f3388eea723a4f92a4eb8302 # v4.0.0
        if: steps.asdf-cache.outputs.cache-hit != 'true'
        with:
          tool_versions: ${{ env.TOOL_VERSIONS }}
          asdf_version: ${{ env.ASDF_BRANCH_VERSION }}

      - name: Prepare committer information and set GPG key
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SCM_COMMITTER_PGP_KEY: ${{ secrets.CI_GPG_SECRET_KEY }}
        run: |
          git config --global credential.helper store
          cat <<EOT >> ~/.git-credentials
          https://ci-user:$GITHUB_TOKEN@github.com
          EOT

          echo "$SCM_COMMITTER_PGP_KEY" | gpg --batch --import
          git config user.name "InditexTech CI"
          git config user.email "oso@inditex.com"

      - name: Update CHANGELOG.md
        id: update-changelog
        uses: release-flow/keep-a-changelog-action@v3.0.0
        with:
          command: bump
          version: ${{ needs.prepare-release.outputs.release_type }}
          changelog: code/CHANGELOG.md
          fail-on-empty-release-notes: false
          keep-unreleased-section: true
          tag-prefix: ""

      - name: NPM / Prepare release version
        working-directory: code
        env:
          RELEASE_VERSION: ${{ needs.publish-release.outputs.final_version }}
        run: |
          npm run version:release

      - name: Release / Commit and Tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_VERSION: ${{ needs.publish-release.outputs.final_version }}
        working-directory: code
        run: |
          git commit -i CHANGELOG.md -m "chore: Update CHANGELOG with $RELEASE_VERSION version" --no-verify
          git commit -i package.json package-lock.json packages/*/package.json -m "[npm-scripts] Release $RELEASE_VERSION" --no-verify
          git tag $RELEASE_VERSION
          git push --atomic --no-verify origin HEAD $RELEASE_VERSION

      - name: NPM / Set next development version
        working-directory: code
        run: |
          npm run version:development

      - name: Next Development Iteration / Commit Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        working-directory: code
        run: |
          git commit -i package.json package-lock.json packages/*/package.json -m "[npm-scripts] prepare for next development iteration" --no-verify
          git push --no-verify origin HEAD

      - name: Next Development Iteration / Create Sync Branch PR into Develop
        id: sync-branch-pr
        continue-on-error: true
        if: ${{ vars.DEVELOPMENT_FLOW != 'trunk-based-development' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BASELINE_BRANCH: ${{ needs.prepare-release.outputs.baseline_branch }}
          RELEASE_VERSION: ${{ needs.publish-release.outputs.final_version }}
        run: |
          DEVELOP=${BASELINE_BRANCH/main/develop}
          echo "DEVELOP=$DEVELOP" >> "$GITHUB_OUTPUT"
          # Avoid creating sync PR if the corresponding development branch does not exist
          if [[ -z $(git ls-remote --heads origin "$DEVELOP") ]]; then
            echo "The '$DEVELOP' branch does not exist in remote. Skipping the creation of sync PR"
          else
            git checkout -b "automated/sync-release-$RELEASE_VERSION-to-$DEVELOP"
            git push --no-verify -u origin HEAD
            gh pr create --base "$DEVELOP" \
              --title "Sync release $RELEASE_VERSION to $DEVELOP" \
              --body "**Automated Pull Request**"
          fi

      - name: Github Release / Create
        uses: ncipollo/release-action@2c591bcc8ecdcd2db72b97d6147f871fcd833ba5
        id: github-release
        continue-on-error: true
        with:
          name: ${{ needs.publish-release.outputs.final_version }}
          tag: ${{ needs.publish-release.outputs.final_version }}
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            Check out the [changelog](code/CHANGELOG.md) for version ${{ needs.publish-release.outputs.final_version }}

      - name: Comment in PR / Sync PR creation failed
        if: ${{ vars.DEVELOPMENT_FLOW != 'trunk-based-development' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BASELINE_BRANCH: ${{ needs.prepare-release.outputs.baseline_branch }}
          RELEASE_VERSION: ${{ needs.publish-release.outputs.final_version }}
        run: |
          DEVELOP=${BASELINE_BRANCH/main/develop}
          git remote set-url origin "https://x-access-token:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY"
          # shellcheck disable=SC2140
          if ! git ls-remote --exit-code --heads origin automated/sync-release-"$RELEASE_VERSION"-to-"$DEVELOP"; then
            gh pr comment "${{ github.event.number }}" --body "An error occurred creating the \`sync\` branch that synchronizes the \`$BASELINE_BRANCH\` and \`$DEVELOP\` branches.
            Please create a branch from \`$BASELINE_BRANCH\` (e.g. \`internal/sync-$BASELINE_BRANCH-with-$DEVELOP\`) and then create a pull request against \`$DEVELOP\` to finish the release process."
          fi

      - name: Comment in PR / Release creation failed
        if: ${{ steps.github-release.outcome == 'failure' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: >
          gh pr comment ${{ github.event.number }} --body "An error occurred creating the Github Release.
          Don't panic! Your artifacts were successfully uploaded to the InditexTech npmjs registry and the new release tag was created.
          You can manually complete the release by creating it in the [releases](https://github.com/${{ github.repository }}/releases)
          page."
